import React from "react";

export function TLSkeleton() {
	return (
		<>
			<article className="skeleton mt-10 rounded-2xl md:w-[600px] sm:w-[500px] w-full p-5  bg-zinc-800">
				<div className="w-[550px] h-6 rounded-md bg-zinc-600"> </div>
				<div className="w-64 h-6 mt-1 bg-zinc-600 rounded-md"> </div>
				<img
					className="w-full rounded-md mt-4"
					src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHCAcHBwcHBwcHBwoHBwcHBw8ICQcKFREWFhURExMYHCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OFRAPFSsZFR0rKysrKy0tLS0tKy0tKzc3Ny0rKzcrKzctLSstNysrLSsrKy03KystKysrKysrKysrK//AABEIAKgBKwMBIgACEQEDEQH/xAAVAAEBAAAAAAAAAAAAAAAAAAAABv/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAABMf/aAAwDAQACEQMRAD8AlwAAAAAAAAAAAAAAAAAAAAAAAAAAAAFABAAAAAAXQAQAAAAAAAAAAAAAAAFAAAAABAAUAEABQAQAAAAAFABAAAAAAAAAAAAAAUAAAEAAAAABQAAAAAQAFAAABAAAAUAEAAAAAAAAAAABQAQAAAAAAAAAAAAAAAAAFAAAAABAAAAAAAAUAAAEAAAAAAAAAAAAAAAAAAABQAQAFABAAAAAAUAEAAAAABQAQAAAFABAAAAAAAAAAAAAAAAAAAAUAEAAAAAAAAAAAAAAAAAAAAAAABQAAAQAAAAAAAAAAAAAFAAABAAAAAAAAAAAAAAAAAAAAAAUAEAAABQAQAFABAAAAAAAAAAAAAAAAAAAAAAAAAAUAEABQAQAFAAABAAAAAAAAAAAAAAUAEAAAAABQAQAAAFABAAAAWgAgAKACAAAAtAAgAIAAAAAAACwAEABYP/Z"
				/>
				<div className="w-28 h-6 mt-5 bg-zinc-600 rounded-md"> </div>
			</article>

			<article className="skeleton mt-10 rounded-2xl md:w-[600px] sm:w-[500px] w-full p-5  bg-zinc-800">
				<div className="w-[550px] h-6 rounded-md bg-zinc-600"> </div>
				<div className="w-64 h-6 mt-1 bg-zinc-600 rounded-md"> </div>
				<img
					className="w-full rounded-md mt-4"
					src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHCAcHBwcHBwcHBwoHBwcHBw8ICQcKFREWFhURExMYHCggGBolGxMTITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OFRAPFSsZFR0rKysrKy0tLS0tKy0tKzc3Ny0rKzcrKzctLSstNysrLSsrKy03KystKysrKysrKysrK//AABEIAKgBKwMBIgACEQEDEQH/xAAVAAEBAAAAAAAAAAAAAAAAAAAABv/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAABMf/aAAwDAQACEQMRAD8AlwAAAAAAAAAAAAAAAAAAAAAAAAAAAAFABAAAAAAXQAQAAAAAAAAAAAAAAAFAAAAABAAUAEABQAQAAAAAFABAAAAAAAAAAAAAAUAAAEAAAAABQAAAAAQAFAAABAAAAUAEAAAAAAAAAAABQAQAAAAAAAAAAAAAAAAAFAAAAABAAAAAAAAUAAAEAAAAAAAAAAAAAAAAAAABQAQAFABAAAAAAUAEAAAAABQAQAAAFABAAAAAAAAAAAAAAAAAAAAUAEAAAAAAAAAAAAAAAAAAAAAAABQAAAQAAAAAAAAAAAAAFAAABAAAAAAAAAAAAAAAAAAAAAAUAEAAABQAQAFABAAAAAAAAAAAAAAAAAAAAAAAAAAUAEABQAQAFAAABAAAAAAAAAAAAAAUAEAAAAABQAQAAAFABAAAAWgAgAKACAAAAtAAgAIAAAAAAACwAEABYP/Z"
				/>
				<div className="w-28 h-6 mt-5 bg-zinc-600 rounded-md"> </div>
			</article>
		</>
	);
}
